### ISSUE TITLE
Can HiNet be proved to be invertible？

### ISSUE THREAD

**Issue by reliarui** [TomTomTommi/HiNet#10]
I learned that the determinant of the Jacobian matrix of a Invertible neural network should be equal to 1, but HiNet's determinant of the Jacobian matrix is not 1 seemingly.

**Comment by TomTomTommi** [comment]
Hi, if I correctly understand your question, in this work, HiNet's determinant of the Jacobian matrix is not considered. In my understanding, for invertible networks, the determinant of the Jacobian matrix is used only when the negative log-likelihood loss is used. But in this work, only L2 loss is used. The reason why we call it is invertible is that we use the affine coupling layer which has the same set of parameters for both the forward and backward process.

**Comment by reliarui** [comment]
Thanks for you answer.
