### ISSUE TITLE
environment.yml创建环境出错

### ISSUE THREAD

**Issue by 3625365git-tx** [TomTomTommi/HiNet#2]
你好，请问我用命令conda env create -f environment.yml创建环境总是报错ResolvePackageNotFound:，
这个怎么解决呢

**Comment by TomTomTommi** [comment]
您好，environment.yml仅用于显示环境版本信息，建议您直接使用conda install 安装需要的package

**Comment by 3625365git-tx** [comment]
好的谢谢

**Comment by RorschachChen** [comment]
在Linux环境下好像可以直接创建
