### ISSUE TITLE
bug with batchsize_val in config.py

### ISSUE THREAD

**Issue by RorschachChen** [TomTomTommi/HiNet#3]
Hi, Tommy. Firstly, congrats for your publication in ICCV2021. 
But I found a small bug in your implementation. The batchsize_val in config.py should be at least 2*number of gpus and it should be divisible by number of gpus, otherwise during backward stage of validation, there will be a error as following.
"TypeError: forward() missing 1 required positional argument: 'x'" 
Besides, I tried batch_size 16, it takes around 22G of cuda memory to run. Hope you can add this reminder to the README as a kind  notification for those who seeks to experiment and learn something from your valuable code and great work. Thanks.

**Comment by TomTomTommi** [comment]
Thanks a lot for your valuable advice!
