### ISSUE TITLE
quantization?

### ISSUE THREAD

**Issue by xhb666** [TomTomTommi/HiNet#4]
Do you consider quantization step? Could you tell me where it is? Thank you very much.

**Comment by TomTomTommi** [comment]
Thanks. According to the previous works https://github.com/muziyongshixin/pytorch-Deep-Steganography and https://github.com/m607stars/MultiImageSteganography, we did not consider the quantization step.

**Comment by xhb666** [comment]
OK, I see. Thank you.

**Comment by TomTomTommi** [comment]
Thanks for the constructive issue. This problem is a drawback in this work and maybe our future work.
