### ISSUE TITLE
Hi, how to obtain your testing sets?

### ISSUE THREAD

**Issue by ddghjikle** [TomTomTommi/HiNet#5]
Thanks a lot for sharing this excellent work. However, according to the paper, the testing datasets include DIV2K [1] testing dataset with 100 images at resolution 1024 × 1024, ImageNet [25] with 50,000 images at resolution 256 × 256, and COCO [17] dataset with 5,000 images at resolution 256 × 256. It seems that images in the testing datasets are randomly chosen from their original datasets. Therefore, could you please release the testing datasets used in your paper?

**Comment by TomTomTommi** [comment]
Thanks. As can be seen in https://github.com/TomTomTommi/HiNet/blob/4409a70a82edc23eef5f467bf3143d59a4ad8020/datasets.py#L71, images in the testing datasets are chosen in order from their original datasets.
In addition, we adopt center crop in https://github.com/TomTomTommi/HiNet/blob/4409a70a82edc23eef5f467bf3143d59a4ad8020/datasets.py#L53. Therefore, the images are calculated by order, and you can obtain the testing datasets simply by running the codes.

**Comment by ddghjikle** [comment]
Thanks very much. By your comments, it means that what I need to do is to place standard DIV2K dataset, ImageNet dataset, and COCO dataset into corresponding path. Then the codes can automatically choose testing images from these datasets. Am I right?

**Comment by TomTomTommi** [comment]
Yes, your understanding is right.

**Comment by ddghjikle** [comment]
Thanks very much!
