### ISSUE TITLE
Question about MAE and RMSE reported in paper

### ISSUE THREAD

**Issue by minzhang-1** [TomTomTommi/HiNet#7]
What is the MAE and RMSE calculated on? RGB image or Y channel?

**Comment by TomTomTommi** [comment]
RGB.
See [calculate_APD_RMSE.py](https://github.com/TomTomTommi/DeepMIH/blob/main/calculate_APD_RMSE.py) for more information.

**Comment by minzhang-1** [comment]
> RGB. See [calculate_APD_RMSE.py](https://github.com/TomTomTommi/DeepMIH/blob/main/calculate_APD_RMSE.py) for more information.

I tried this function, but the rmse and mae values are over one hundred.

**Comment by minzhang-1** [comment]
And for PSNR, the test results using your pretrained model for DIV2K and ImageNet are 2dB better than that in your paper. Is that normal? Just to confirm, DIV2K, COCO and ImageNet testing sets are actually validation sets, right?

**Comment by TomTomTommi** [comment]
Hi, I have re-checked the calculated_APD_RMSE.py code and the results are normal.
The pre-trained model provided is the result after polishing and re-training the code, so it may be a little different from that in the paper. This is normal. And for datasets, your understanding is correct.

**Comment by TomTomTommi** [comment]
![image](https://user-images.githubusercontent.com/34483135/152626606-546afe0d-eb98-4d67-a1dd-7416f0880789.png)

**Comment by minzhang-1** [comment]
> Hi, I have re-checked the calculated_APD_RMSE.py code and the results are normal. The pre-trained model provided is the result after polishing and re-training the code, so it may be a little different from that in the paper. This is normal. And for datasets, your understanding is correct.

Hi, thanks for your reply. I find the abnormality of MAE and RMSE are due to the bgr2ycbcr function which changed the value of the input image. It maybe caused by different versions of python, etc. Anyway, it works now. Besides, since you didn't use quantization before backward pass, does that mean if we only have a stego image, we can't recover the same quality secret and cover image as you reported since the pipeline is not optimized for a quantized image? Whether the other methods in the comparison table use quantization or not? Thanks for your patience!

**Comment by TomTomTommi** [comment]
Thanks. According to the previous works https://github.com/muziyongshixin/pytorch-Deep-Steganography and https://github.com/m607stars/MultiImageSteganography, we did not consider the quantization step. The results in the comparison table are all without quantization. This is a shortage of our work, which may be a future direction. The operation of quantization and other distortion ways are common in watermarking, while it would be a good idea to apply in image hiding.
